create table if not exists public.welcome_messages (
  id bigint generated by default as identity primary key,
  message text not null check (char_length(message) between 1 and 120),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.welcome_messages enable row level security;

revoke all on table public.welcome_messages from anon, authenticated;
grant select on table public.welcome_messages to anon, authenticated;

drop policy if exists "Welcome messages are publicly readable" on public.welcome_messages;
create policy "Welcome messages are publicly readable"
on public.welcome_messages
for select
to anon, authenticated
using (active = true);

insert into public.welcome_messages (message, active)
select 'Bienvenido', true
where not exists (select 1 from public.welcome_messages);
